### ISSUE TITLE
About your evaluation metric zR@K

### ISSUE THREAD

**Issue by yuxha** [Wayfear/Coacher#1]
Thanks for your work!

I am confused when I compare your experimental results with the results of your base code (SGG Benchmark Project).
[https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/METRICS.md#explanation-of-our-metrics](url)

I notice that the zR@Ks in your paper are much more than the zR@Ks in SGG Benchmark Project (About 10 times)

For example, the zR@20 of NeuralMotifs reported in SGG Benchmark Project is 1%, but 13% in your paper.

Can you explain why? Thank you very much.

**Comment by ZHUXUHAN** [comment]
> Thanks for your work!
> 
> I am confused when I compare your experimental results with the results of your base code (SGG Benchmark Project). [https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/METRICS.md#explanation-of-our-metrics](url)
> 
> I notice that the zR@Ks in your paper are much more than the zR@Ks in SGG Benchmark Project (About 10 times)
> 
> For example, the zR@20 of NeuralMotifs reported in SGG Benchmark Project is 1%, but 13% in your paper.
> 
> Can you explain why? Thank you very much.

hi, do you know why?
